apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawk-HASH
  namespace: hawk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hawk-HASH
  template:
    metadata:
      name: hawk-HASH
      namespace: hawk
      labels:
        app: hawk-HASH
    spec:
      containers:
      - name: hawk-HASH-container
        image: python:3.11-slim
        command: ['bash', '-c']
        args: ['python3 -m pip install -r /app/requirements.txt && sleep 300 && python3 /app/script.py']
        volumeMounts:
        - name: config-volume
          mountPath: /app
      volumes:
      - name: config-volume
        configMap:
          name: hawk-HASH-config

