apiVersion: apps/v1
kind: Deployment
metadata:
  name: hawk-db
  namespace: hawk
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hawk-db
  template:
    metadata:
      name: hawk-db
      namespace: hawk
      labels:
        app: hawk-db
    spec:
      containers:
      - name: hawk-db-container
        image: mongo
